version: "3.4"

services:
  dashboard:
    container_name: hf-dashboard
    build:
      context: .
      dockerfile: src/Dashboard/Dockerfile
      args:
        - BUILDMODE
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  worker:
    container_name: hf-worker
    build:
      context: .
      dockerfile: src/Worker/Dockerfile
      args:
        - BUILDMODE
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  workflow.api:
    container_name: hf-workflow-api
    build:
      context: .
      dockerfile: src/Workflow.Api/Dockerfile
      args:
        - BUILDMODE
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

networks:
  app-network:
    external:
      name: rimu-meta-eu1-devtools_app-network
